# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Latent Factor modeling using Stochastic Gradient Descent
#' @description Decompose a matrix R to minimize
#'     ||R - b_u * 1 + 1 * b_i' - PQ||_{F}^{2} + lambda_1 * ||b_{u}||_{2}^{2} +
#'        lambda_2 * ||b_i||_{2}^{2} + lambda_3 * ||P||_{F}^{2} +
#'        lambda_4 * ||Q||_{F}^{2}
#' @param R A user x item matrix of ratings.
#' @param obs_ix A n_obs x 2 matrix whose rows give indices at which ratings
#' were observed.
#' @param lambdas A vector of regularization parameters, as in the objective
#' function given above.
#' @param eta The learning rate for the stochastic gradient descent.
#' @param iter_max The number of iterations to run the SGD.
#' @param d The dimension of the latent factors.
#' @return The fitted parameters from the objective function below, \cr
#'    bu: Bias terms for each user. \cr
#'    bi: Bias terms for each item. \cr
#'    P: A user x d latent factor matrix for users \cr.
#'    Q: A item x d latent factor matrix for items.
#' @export
lf_sgd <- function(R, obs_ix, lambdas, eta = 0.05, iter_max = 1000L, d = 5L) {
    .Call('emi_lf_sgd', PACKAGE = 'emi', R, obs_ix, lambdas, eta, iter_max, d)
}

