# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_batch_ix <- function(n, p) {
    .Call('emi_get_batch_ix', PACKAGE = 'emi', n, p)
}

#' @title Gradient step for Latent Factors
#' @param x Either a single row or single column of X, the ratings matrix.
#' @param z A single matrix from the covariates array, associated with the
#' either a single row or column of X.
#' @param p_i The latent factors associated with a single user or track.
#' @param Q The latent factors associated with either all tracks or all users,
#' depending on the type of latent factor in p_i.
#' @param beta The learned regression coefficients.
#' @param lambda The regularization parameter for the current latent factor.
#' @param batch_samples The proportion of the observed entries to sample in the
#' gradient for each factor in the gradient descent.
#' @param gamma The step-size in the gradient descent.
#' @return The update latent factor for the current user / track.
#' @export
update_factor <- function(x, z, p_i, Q, beta, lambda, batch_samples, gamma) {
    .Call('emi_update_factor', PACKAGE = 'emi', x, z, p_i, Q, beta, lambda, batch_samples, gamma)
}

#' @title Regular gradient descent for latent factor model with covariates
#' @param X The ratings matrix. Unobserved entries must be marked NA. Users
#' must be along rows, and tracks must be along columns.
#' @param Z The covariates associated with each pair. This must be shaped as an
#' array with users along rows, tracks along columns, and features along
#' slices.
#' @param k_factors The number of latent factors for the problem.
#' @param lambdas The regularization parameters for P, Q, and beta, respectively.
#' @param n_iter The number of gradient descent iterations to run.
#' @param batch_samples The proportion of the observed entries to sample in the
#' gradient for each factor in the gradient descent.
#' @param batch_factors The proportion of latent factors to update at each
#' iteration.
#' @param gamma The step-size in the gradient descent.
#' @return A list with the following elements, \cr
#'   $P The learned user latent factors. \cr
#'   $Q The learned track latent factors.
#'   $beta The learned regression coefficients.
#' @export
lf_gd_cov <- function(X, Z_vec, k_factors, lambdas, n_iter, batch_samples, batch_factors, gamma_pq, gamma_beta) {
    .Call('emi_lf_gd_cov', PACKAGE = 'emi', X, Z_vec, k_factors, lambdas, n_iter, batch_samples, batch_factors, gamma_pq, gamma_beta)
}

#' @title Latent Factor modeling using Stochastic Gradient Descent
#' @description Decompose a matrix R to minimize
#'     ||R - b_u * 1 + 1 * b_i' - PQ||_{F}^{2} + lambda_1 * ||b_{u}||_{2}^{2} +
#'        lambda_2 * ||b_i||_{2}^{2} + lambda_3 * ||P||_{F}^{2} +
#'        lambda_4 * ||Q||_{F}^{2}
#' @param R A user x item matrix of ratings.
#' @param obs_ix A n_obs x 2 matrix whose rows give indices at which ratings
#' were observed.
#' @param lambdas A vector of regularization parameters, as in the objective
#' function given above.
#' @param eta The learning rate for the stochastic gradient descent.
#' @param iter_max The number of iterations to run the SGD.
#' @param d The dimension of the latent factors.
#' @return The fitted parameters from the objective function below, \cr
#'    bu: Bias terms for each user. \cr
#'    bi: Bias terms for each item. \cr
#'    P: A user x d latent factor matrix for users \cr.
#'    Q: A item x d latent factor matrix for items.
#' @export
lf_sgd <- function(R, obs_ix, lambdas, eta = 0.05, iter_max = 1000L, d = 5L) {
    .Call('emi_lf_sgd', PACKAGE = 'emi', R, obs_ix, lambdas, eta, iter_max, d)
}

