// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// lf_sgd
List lf_sgd(NumericMatrix R, IntegerMatrix obs_ix, NumericVector lambdas, double eta, int iter_max, int d);
RcppExport SEXP emi_lf_sgd(SEXP RSEXP, SEXP obs_ixSEXP, SEXP lambdasSEXP, SEXP etaSEXP, SEXP iter_maxSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type R(RSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type obs_ix(obs_ixSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambdas(lambdasSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< int >::type iter_max(iter_maxSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    __result = Rcpp::wrap(lf_sgd(R, obs_ix, lambdas, eta, iter_max, d));
    return __result;
END_RCPP
}
// get_batch_ix
arma::uvec get_batch_ix(int n, double p);
RcppExport SEXP emi_get_batch_ix(SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    __result = Rcpp::wrap(get_batch_ix(n, p));
    return __result;
END_RCPP
}
// update_factor
arma::vec update_factor(arma::vec x, arma::mat z, arma::vec p_i, arma::mat Q, arma::vec beta, double lambda, double batch_samples, double gamma);
RcppExport SEXP emi_update_factor(SEXP xSEXP, SEXP zSEXP, SEXP p_iSEXP, SEXP QSEXP, SEXP betaSEXP, SEXP lambdaSEXP, SEXP batch_samplesSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type p_i(p_iSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type batch_samples(batch_samplesSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    __result = Rcpp::wrap(update_factor(x, z, p_i, Q, beta, lambda, batch_samples, gamma));
    return __result;
END_RCPP
}
// svd_cov
Rcpp::List svd_cov(Rcpp::NumericMatrix X, Rcpp::NumericVector Z_vec, int k_factors, Rcpp::NumericVector lambdas, int n_iter, double batch_samples, double batch_factors, double gamma_pq, double gamma_beta);
RcppExport SEXP emi_svd_cov(SEXP XSEXP, SEXP Z_vecSEXP, SEXP k_factorsSEXP, SEXP lambdasSEXP, SEXP n_iterSEXP, SEXP batch_samplesSEXP, SEXP batch_factorsSEXP, SEXP gamma_pqSEXP, SEXP gamma_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Z_vec(Z_vecSEXP);
    Rcpp::traits::input_parameter< int >::type k_factors(k_factorsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambdas(lambdasSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< double >::type batch_samples(batch_samplesSEXP);
    Rcpp::traits::input_parameter< double >::type batch_factors(batch_factorsSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_pq(gamma_pqSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_beta(gamma_betaSEXP);
    __result = Rcpp::wrap(svd_cov(X, Z_vec, k_factors, lambdas, n_iter, batch_samples, batch_factors, gamma_pq, gamma_beta));
    return __result;
END_RCPP
}
