// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// lf_sgd
List lf_sgd(NumericMatrix R, IntegerMatrix obs_ix, NumericVector lambdas, double eta, int iter_max, int d);
RcppExport SEXP emi_lf_sgd(SEXP RSEXP, SEXP obs_ixSEXP, SEXP lambdasSEXP, SEXP etaSEXP, SEXP iter_maxSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type R(RSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type obs_ix(obs_ixSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambdas(lambdasSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< int >::type iter_max(iter_maxSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    __result = Rcpp::wrap(lf_sgd(R, obs_ix, lambdas, eta, iter_max, d));
    return __result;
END_RCPP
}
